In [461]:
import pandas as pd
import datetime
from pandas._libs.tslibs.parsing import DateParseError
import json

In [328]:
df = pd.read_csv("/app/data/202309.csv",dtype=str)
# df2 = pd.read_csv("/app/data/202307.csv")
# print(type(df2["date"][0]))
# type(pd.to_datetime(df["date"][0]))
data = pd.DataFrame(columns=("date","part","exercise","weight","number_of_times"))
part = ["背中","胸","脚","腹筋","肩","腕"]

In [458]:
# try:
#     t = type(pd.to_datetime(df["date"][1]))
# except DateParseError:
#     print(123455656)
with open('app/data/data.json') as f:
    ex_json = json.load(f)
    
part_list = []
date_list = []
ex_list = []
training_list = []
# pd.to_datetime(df["date"][1])
for i in range(len(df)):
    # if df["date"][i] == "11111":

    try:
        training_date = pd.to_datetime(df["date"][i])
        each_dict = {"date": df["date"][i]}
    except DateParseError:
        if df["date"][i] in ex_json["part"]:
            each_dict["part"] = df["date"][i]
            each_dict["exercise"] = {}
        if df["date"][i] in each_dict["part"]:
            each_dict["exercise"][df["date"][i+1]] = []
            part = df["date"][i+1]
            for j in range(i+2,i+10):
                if df["date"][j].count("×")==1:
                    each_dict["exercise"][part].append(df["date"][j].split("×"))
                else:
                    training_list.append(each_dict)
                    i += len()
            
        # date = training_date.year + '-' + training_date.month + '-' + training_date.day
        # each_dict = {
        #     "date": 
        #     training_date, "part": part, "exercise":{df["date"][i+2]:[]}
        # }
        # セット数（上限10を想定
        # if  each_dict["part"] == each_dict["part"]:
        #     for j in range(i+2,i+10):
        #         if df["date"][j].count("×") == 1:
        #             each_dict["exercise"][df["date"][i+2]].append(df["date"][j].split("×"))
        #         else:
        #             training_list.append(each_dict)
        #             break
    
    # except IndexError:
    #     continue
    # except KeyError:
    #     continue

TypeError: len() takes exactly one argument (0 given)

In [344]:
# JSON 文字列が空でないことを確認し、適切な JSON 形式であることを確認する
json_string = '{"name": [], "age": 30, "city": "New York"}'

# JSON 文字列を解析する
try:
    data = json.loads(json_string)
    print(data)
except json.JSONDecodeError as e:
    print("JSON 解析エラー:", e)

{'name': [], 'age': 30, 'city': 'New York'}

In [483]:
df = pd.read_csv("/app/data/202403.csv",sep=',')
df.to_excel("/app/data/トレーニング管理.xlsx",index=False,sheet_name='202403')
df

          date part exercise  weight  number_of_times
0   2024-03-01   背中   デッドリフト   110.0                4
1   2024-03-01   背中   デッドリフト   100.0                7
2   2024-03-01   背中   デッドリフト   100.0                5
3   2024-03-01   背中   デッドリフト    90.0                8
4   2024-03-01   背中   デッドリフト    80.0                8
..         ...  ...      ...     ...              ...
78  2024-03-14    脚    スクワット   100.0                2
79  2024-03-14    脚   レッグプレス   118.0                8
80  2024-03-14    脚   レッグプレス   118.0                8
81  2024-03-14    脚   レッグプレス   127.0                5
82  2024-03-14    脚   レッグプレス   127.0                6

[83 rows x 5 columns]

In [490]:
with pd.ExcelWriter("/app/data/トレーニング管理.xlsx", engine="openpyxl", mode="a") as writer:
	df = pd.read_csv("/app/data/202404.csv",sep=',')
	df.to_excel(writer,index=False,sheet_name='202404')